# Generated by Django 4.2.6 on 2024-11-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_description', models.TextField()),
                ('time_reported', models.DateTimeField()),
                ('time_occurred', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('current_status', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.block')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('type_code', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('type_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_code', models.AutoField(primary_key=True, serialize=False)),
                ('weapon_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Visitor', 'Visitor'), ('Related', 'Related Person'), ('Officer', 'Officer'), ('Cid', 'Criminal Investigator'), ('Admin', 'Administrator')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='residents/')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.block')),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.resident')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeEventWeap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_detail', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimetype')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeEventPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('supervisor', 'Supervisor')], max_length=10)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.police')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeEventPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Susp', 'Suspect'), ('Crim', 'Criminal'), ('Vict', 'Victim'), ('Eyew', 'Eyewitness'), ('Witn', 'Witness')], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.resident')),
            ],
        ),
        migrations.AddField(
            model_name='crimeevent',
            name='main_criminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes_committed', to='crime.resident'),
        ),
        migrations.AddField(
            model_name='crimeevent',
            name='main_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crime.crimetype'),
        ),
        migrations.AddField(
            model_name='crimeevent',
            name='main_victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes_victimized', to='crime.resident'),
        ),
        migrations.AddField(
            model_name='crimeevent',
            name='main_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime.weapon'),
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clue_code', models.AutoField(primary_key=True, serialize=False)),
                ('clue_type', models.CharField(default='General', max_length=50)),
                ('clue_description', models.TextField()),
                ('clue_image', models.ImageField(blank=True, null=True, upload_to='clues/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_as_evidence', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_police', models.BooleanField(default=False)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.police')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.resident')),
            ],
        ),
        migrations.CreateModel(
            name='CaseProgress',
            fields=[
                ('progress_code', models.AutoField(primary_key=True, serialize=False)),
                ('time_progress', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crimeevent')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
